# Simple workflow for deploying static content to Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: rustup toolchain install nightly
      - run: rustup default nightly
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install trunk
      - run: trunk build --release
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: deploy
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Run server on Windows
        if: runner.os == 'Windows'
        run: cargo run
      - name: Serve with Trunk on wasm
        if: runner.os != 'Windows'
        run: trunk serve
